server:
  port: 8086

#————————————————————————————————————————————————————————————————————————————————

#在 Eureka 开启认证后，客户端注册的配置也要加上认证的用户名和密码信息：
eureka:
  client:
    service-url:
      defaultZone: http://qty:qty@127.0.0.1:8080/eureka/
    #自定义 Eureka 的 InstanceID，格式 —— 服务名称：服务所在 IP：服务端口
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}


#—————————————————————————————————————————————————————————————————————————————————————————————————————————

# uri 以 lb：//开头（lb 代表从注册中心获取服务），
#  后面接的就是你需要转发到的服务名称，这个服务名称必须跟 Eureka 中的对应，否则会找不到服务，错误代码如下：
#  org.springframework.cloud.gateway.support.NotFoundException: Unable to find instance for user-service1
#spring:
#  application:
#    name: springcloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: springcloud-provider
#          uri: lb://springcloud-provider
#          #断言
#          predicates:
#            - Path=/springcloud-provider*
#      #为所有服务都进行转发操作
#      discovery:
#        locator:
#          enabled: true
#          #开启小写服务名称后大写的服务名称就不能使用，两者只能选其一。
#          lowerCaseServiceId: true
#  - id: path_route
#      uri: http://c.biancheng.net
#      predicates:
#        - Path=/springcloud

#——————————————————————————————————————————————————————————————————————————————————————————————————————————

#——————————————————————————————————————————断言工厂———————————————————————————————————————————————————————

#1、Path 路由断言工厂
#  根据 Path 定义好的规则来判断访问的 URI 是否匹配
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: host_route
#          uri: http://c.biancheng.net
#          predicates:
#            - Path=/blog/detail/{segment}


#2、Query 路由断言工厂
#  Query 路由断言工厂接收两个参数，一个必需的参数和一个可选的正则表达式。
#  如果请求包含一个值与 ba 匹配的 foo 查询参数，则此路由将匹配。bar 和 baz 也会匹配，因为第二个参数是正则表达式。
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: query_route
#          uri: http://c.biancheng.net
#          predicates:
#            - Query=foo, ba.


#3、Method 路由断言工厂
#  Method 路由断言工厂接收一个参数，即要匹配的 HTTP 方法。
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: method_route
#          uri: http://baidu.com
#          predicates:
#            - Method=GET


#4、Header 路由断言工厂
#  Header 路由断言工厂接收两个参数，分别是请求头名称和正则表达式。
#  如果请求中带有请求头名为 x-request-id，其值与 \d+ 正则表达式匹配（值为一个或多个数字），则此路由匹配。
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: header_route
#          uri: http://example.org
#          predicates:
#            - Header=X-Request-Id, \d+

#——————————————————————————————————————————————————————————————————————————————————————————————————————————

#——————————————————————————————————————————过滤器信息————————————————————————————————————————————————————

#1、ip限流

#spring:
#  application:
#    name: springcloud-gateway
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  cloud:
#    gateway:
#      routes:
#        - id: springcloud-provider
#          uri: lb://springcloud-provider
#          #断言
#          predicates:
#            - Path=/springcloud-provider*
#            - RemoteAddr=192.168.1.28
#      #为所有服务都进行转发操作
#      discovery:
#        locator:
#          enabled: true
#          #开启小写服务名称后大写的服务名称就不能使用，两者只能选其一。
#          lowerCaseServiceId: true
##      filter 名称必须是 RequestRateLimiter。
##      redis-rate-limiter.replenishRate：允许用户每秒处理多少个请求。
##      redis-rate-limiter.burstCapacity：令牌桶的容量，允许在 1s 内完成的最大请求数。
##      key-resolver：使用 SpEL 按名称引用 bean。
#      filter:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 10
#            redis-rate-limiter.burstCapacity: 20
#            key-resolver: "#{@ipKeyResolver}"

#——————————————————————————————————————————————————————————————————————————————————————————————————————


#—————————————————————————————————————————————熔断回退——————————————————————————————————————————————————

#内置了 HystrixGatewayFilterFactory 来实现路由级别的熔断，只需要配置即可实现熔断回退功能
#spring:
#  application:
#    name: springcloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: springcloud-provider
#          uri: lb://springcloud-provider
#          #断言
#          predicates:
#            - Path=/springcloud-provider*
#          filter:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                #           fallbackUri 是发生熔断时回退的 URI 地址，目前只支持 forward 模式的 URI。如果服务被降级，该请求会被转发到该 URI 中。
#                fallbackUri: forward:/fallback
#      #为所有服务都进行转发操作
#      discovery:
#        locator:
#          enabled: true
#          #开启小写服务名称后大写的服务名称就不能使用，两者只能选其一。
#          lowerCaseServiceId: true
#      #      filter 名称必须是 Hystrix。

#——————————————————————————————————————————————————————————————————————————————————————————

#——————————————————————————————————————————跨域————————————————————————————————————————————

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            exposedHeaders:
              - content-type
            allowedHeaders:
              - content-type
            allowCredentials: true
              allowedMethods:
                - GET
                - OPTIONS
                - PUT
                - DELETE
                - POST

